# Music Data Indicators {#music-data}

With no particular order

## Music Economy

### Demand Drivers

Our music economy [demand drivers](https://data.music.dataobservatory.eu/music-economy.html) are data that are known to be leading indicators to an increase in mechanical copies, streaming subscriptions, public performance use, private copying or illegal use of music.

### Supply Indicators

Our Music Economy / [Supply](https://data.music.dataobservatory.eu/music-economy.html#supply) indicators are related to the supply of new music.  

### Price Indicators



## Music Diversity

### Gender, Language, Ethnic and Other Inclusion Attributes

## Music Circulation

### Market shares


We are developing [market share](https://data.music.dataobservatory.eu/music-diversity.html#cross-border-circulation-of-works) indicators for streaming and broadcast music. 

For national, gender or other market share, we need to label both music works and recorded fixations.  We use various open source databases, and machine learning algorithms to do prepare the data, but eventually our data goes through human musicology or music journalist curators. 

For example, in our case study we were interested in the various definitions of `Slovak market share`, and representation of `female artists.` Both problems require rather challenging labeling.

a) we tried to find a location to the artist / band [ you can describe why this is not always straightforward, for example, in the case of dead artists, etc.]
b) our algorithm tried to guess the language of the 10 most popular song titles
c) we checked if the person is on the Wikipedia list of "Slovak male singers",  "Slovak female singers",  "Slovak bands", or their Czechoslovak versions [ who did you decide when somebody was Czechoslovak if they were Slovak] 
d) check if there was a Slovak placename mentioned on their bandcamp site
e) check if they are associated with Slovakia on the Musicbrainz open source database
f) if any of the artists released recodings was released in Slovakia
g) if the majority of the artist's released recordings was released in Slovakia

....

Until we got to the human curation. 

and eventually we either `considered_slovak` or not somebody in our `write-in database`.  We are also developing an `opt-in database`, where artists can give us their own ethnic, local and gender identity, if they wish to, and of course, they can opt-out from our labeling.

We are using Monte Carlo simulation and non-parametric sampling of various broadcast and music streams to get a representation of the music listened to in various cities, regions, countries, and then we apply `national`, `language`, `gender`, `sex`, `locality` and `folksonomy` tags to measure female, Slovak, Estonian, Amsterdam or Welsh market share, recommendation probability, etc.

## Music & Society

### Social Attitutes to Music

### Participation in Music


